"""
日志检查脚本：诊断熵值扫描问题

使用方法：
1. 运行训练
2. 观察控制台输出
3. 检查日志文件
"""

print("=" * 60)
print("熵值扫描问题诊断指南")
print("=" * 60)

print("\n【步骤1】检查训练开始时的日志")
print("-" * 60)
print("应该看到：")
print("  [4/5] 创建训练环境...")
print("  [OK] 环境创建成功")
print("  [Scan] 扫描进度: 重置模式 (每个Episode重新扫描)")
print("")
print("如果看到'累积模式'，说明配置错误！")
print("  解决：检查train_with_airsim_improved.py第712行")
print("  确保默认值为True")

print("\n【步骤2】检查第一个Episode重置时的日志")
print("-" * 60)
print("应该看到完整的重置流程：")
print("")
print("  🔄 重置环境 - Episode #1")
print("  ==================================================")
print("  [重置] 1/5 执行 AirSim 物理重置 (强制回到地面)")
print("  [重置] 无人机重新起飞...")
print("  [重置] 2/5 清理本地算法与统计数据...")
print("  [重置] 网格熵值已重置为100（完全重新扫描）")
print("  [重置] 3/5 发送重置命令到 Unity，等待反馈 (ACK)...")
print("  [重置] ✅ 收到 Unity 反馈，耗时: X.XXs")
print("  [重置] 4/5 发送 start_simulation 指令，Leader 开始移动")
print("  [重置] 等待完成，Unity应该已启动熵值收集")
print("  [重置] ✨ 严格重置流程执行完毕，系统已回到初始状态")
print("")

print("如果缺少任何一步，说明Python端有问题！")

print("\n【步骤3】检查算法线程日志")
print("-" * 60)
print("重置后应该看到：")
print("  [UAV1] 重置后同步完成，继续决策")
print("")
print("然后应该看到：")
print("  [UAV1] 首帧同步完成，开始决策循环")
print("  [UAV1] ✅ 位置正常: X.XXm")
print("")
print("如果看到'位置几乎未变'，说明Unity没有响应！")

print("\n【步骤4】检查扫描数据日志")
print("-" * 60)
print("查看训练日志文件：")
print("  tail -20 multirotor/DDPG_Weight/airsim_training_logs/ddpg_training_*.csv")
print("")
print("应该看到每个Episode都有scanned_cells > 0")
print("")
print("如果看到scanned_cells都是0，说明：")
print("  - Unity没有执行扫描")
print("  - 或者扫描结果没有正确返回")

print("\n【步骤5】检查Unity端")
print("-" * 60)
print("在Unity控制台/日志中查找：")
print("  1. 是否收到'reset_env'指令")
print("  2. 是否收到'start_simulation'指令")
print("  3. 是否启动了熵值收集")
print("  4. 是否收到runtime数据")
print("  5. 是否执行了扫描")
print("  6. 是否返回了grid_data")
print("")
print("Unity日志应该显示：")
print("  [Unity] 收到reset_env指令")
print("  [Unity] 重置完成，返回ACK")
print("  [Unity] 收到start_simulation指令")
print("  [Unity] 启动熵值收集")
print("  [Unity] 收到runtime数据")
print("  [Unity] 执行扫描，更新熵值")
print("  [Unity] 发送grid_data")

print("\n【常见问题】")
print("-" * 60)
print("问题1: Python日志缺少'等待完成'")
print("  原因: 代码版本过旧")
print("  解决: 检查AlgorithmServer.py第1913-1916行")
print("")
print("问题2: 算法线程没有'重置后同步完成'")
print("  原因: ready_event未正确设置")
print("  解决: 检查reset_environment第1931行")
print("")
print("问题3: scanned_cells都是0")
print("  原因: Unity端扫描未启动")
print("  解决: 检查Unity端是否正确处理start_simulation")
print("")
print("问题4: 位置几乎未变")
print("  原因: Unity没有响应runtime数据")
print("  解决: 检查Unity通信和算法逻辑")

print("\n【快速诊断】")
print("-" * 60)
print("运行以下命令检查最新训练日志：")
print("")
print("  # 查看最后的重置日志")
print("  grep -A 20 '重置环境' multirotor/DDPG_Weight/logs/ddpg_airsim/*.log | tail -40")
print("")
print("  # 查看start_simulation发送")
print("  grep 'start_simulation' multirotor/DDPG_Weight/logs/ddpg_airsim/*.log")
print("")
print("  # 查看算法线程状态")
print("  grep '重置后同步' multirotor/DDPG_Weight/logs/ddpg_airsim/*.log")
print("")
print("  # 查看扫描数据")
print("  tail -10 multirotor/DDPG_Weight/airsim_training_logs/ddpg_training_*.csv")

print("\n" + "=" * 60)
print("如果以上检查都正常但熵值仍不降低")
print("=" * 60)
print("很可能是Unity端的问题！")
print("")
print("需要在Unity端添加调试日志：")
print("  1. 确认收到start_simulation指令")
print("  2. 确认启动了熵值收集")
print("  3. 确认收到runtime数据")
print("  4. 确认执行了扫描逻辑")
print("  5. 确认返回了更新后的grid_data")
print("")
print("Unity端的扫描逻辑可能需要检查：")
print("  - 扫描距离设置")
print("  - 熵值更新逻辑")
print("  - 数据发送频率")
print("")
print("=" * 60)
